name: "Telecentro Deco"
version: "1.0.0"
author: "Fina Team"
description: "Control de Decodificador Telecentro SEI800TC1 via ADB"
enabled: true
priority: 55
main_file: "tv.py"
main_class: "TVPlugin"
type: "sei800tc1"
